name: Create Stack

on:
  workflow_dispatch:  

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.1

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        
    - name: Run state resources creation script
      run: |
        cd terraform
        chmod +x create-storage-account.sh  
        ./create-storage-account.sh  

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform init 
        terraform apply -auto-approve
