name: Create Stack

on:
  workflow_dispatch:  

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v2

    # Log in to Azure using Service Principal credentials
    - name: Azure Login via Service Principal
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    # Set the Azure subscription
    - name: Set Azure Subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Run state resources creation script
      run: |
        cd terraform
        chmod +x create-storage-account.sh  
        ./create-storage-account.sh  

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform init 
        terraform apply -auto-approve
