name: Create Stack

on:
  workflow_dispatch:  

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Azure Login via Service Principal
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Run state resources creation script
      run: |
        chmod +x create-storage-account.sh  
        ./create-storage-account.sh  

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform init 
        terraform apply -auto-approve
