name: Create Stack

on:
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read
  
jobs:
  create:
    runs-on: ubuntu-latest
    env:  # Define environment variables here
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       # client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        
    - name: Run state resources creation script
      run: |
        cd terraform
        chmod +x create-storage-account.sh  
        ./create-storage-account.sh  

    - name: Run Terraform Apply
      run: |
        cd terraform
        terraform init 
        terraform apply -auto-approve
