name: Delete Stack

on:
  workflow_dispatch:  

jobs:
  create:
    runs-on: ubuntu-latest
    env:  # Define environment variables here
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Terraform Destroy
      run: |
        cd terraform 
        terraform destroy -auto-approve

    - name: Run state resources deletion script
      run: |
        chmod +x delete-storage-account.sh
        ./delete-storage-account.sh
